BITCOIN_ECOSYSTEM = {
    "slug": "bitcoin",
    "display_name": "Bitcoin",
    "proposal_term_singular": "Bitcoin Improvement Proposal",
    "proposal_term_plural": "Bitcoin Improvement Proposals",
    "proposal_acronym": "BIP",
    "repository_owner": "bitcoin",
    "repository_name": "bips",
    "data_root": "ip_data/bitcoin",
    "harvest": "ip_data/bitcoin/01_harvest",
    "preprocess": "ip_data/bitcoin/02_preprocess",
    "analysis": "ip_data/bitcoin/03_analysis",
    "postprocess": "ip_data/bitcoin/04_postprocess",
    "document_prefix": "bip",
    "primary_id_field": "bip",
    "document_file_pattern": r"^bip-\d{4}\.(mediawiki|md|rst)$",
    "document_dir_pattern": r"^bip-\d{4}$",
    "reference_pattern": r"\bBIP[-#\s]?(\d+)\b",
    "stop_words_file": "assets/stopwords/en_basic.txt",
    "preamble": {
        "required_fields": [
            "bip",
            "title",
            "author",
            "comments_uri",
            "status",
            "type",
            "created",
            "license",
        ],
        "optional_fields": [
            "layer",
            "discussions_to",
            "comments_summary",
            "license_code",
            "post_history",
            "requires",
            "replaces",
            "superseded_by",
        ],
        "field_aliases": {
            "authors": "author",
            "assigned": "created",
            "proposed_replacement": "superseded_by",
        },
        "expected_headlines": {
            "abstract": 2,
            "motivation": 2,
            "specification": 2,
            "copyright": 2,
        },
        "list_valued_fields": ["author", "license"],
    },
    "classification": {
        "layer_aliases": {},
        "status_aliases": {
            "Draft (Some confusion applies: The announcements for this never made it to the list, so it hasn't had public discussion)" : "Draft"
            },
        "type_aliases": {
            "Standard": "Standards Track",
            "Standards": "Standards Track",
            "Standard Track": "Standards Track",
            "Standards-Track": "Standards Track",
        },
    },
}
